INSERT INTO MEMBER_SUBSCRIPTION_TYPE (
	MEMBSUBTYPE_CATEGORY,
	MEMSUBTYPE_FULL_YEAR_RATE,
	MEMSUBTYPE_HALF_YEAR_RATE,
	MEMSUBTYPE_DESCRIPTION
) VALUES (
	@category,
	@full_year_rate,
	@half_year_rate,
	@description
);