START TRANSACTION;

	IF NOT EXISTS 
		(SELECT * 
		FROM MEMBER_PAYMENTS 
		WHERE MEMBER_CODE = @member_code 
		AND MEMPAYMENT_DATE > CURDATE() - INTERVAL 1 MONTH) THEN
		
		UPDATE MEMBER_SUBSCRIPTION SET MEMBER_STATUS = 'disabled' WHERE MEMBER_CODE = @member_code;

	END IF;

COMMIT;